version: '3.8'
services:
  srtla-live-server:
    image: moothecow/srtla-live-server:0.0.1
    container_name: srtla-live-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: none
    ports: 
      - "30001:30000/udp"
      - "8283:8181/tcp"
    volumes:
      - ./sls.conf:/etc/sls/sls.conf
  srtla-receiver:
    image: moothecow/srtla-receiver:0.0.2
    container_name: srtla-receiver
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - "5002:5000/udp"
      - "5003:5001/udp"
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
    environment:
      - SRT_ENDPOINT_ADDR=srtla-live-server
      - SRT_ENDPOINT_PORT=30000
    depends_on:
      - "srtla-live-server"
  # RIST
  moo-ffmpeg:
    image: moothecow/moo-ffmpeg-selfhosting-amd64:${VERSION}
    container_name: moo-ffmpeg
    restart: unless-stopped
    tty: true
    logging:
      driver: none
    environment:
      - RIST_RELAY_KEY=${RIST_RELAY_KEY}
    networks:
      network:
        ipv4_address: 172.19.0.6
    depends_on:
      - "srt-live-server"
  srt-live-server:
    image: moothecow/srt-live-server-amd64:0.0.1
    container_name: srt-live-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: none
    networks:
      network:
        ipv4_address: 172.19.0.5
    ports: 
      - "30002:30000/udp"
      - "8284:8181/tcp"
    volumes:
      - ./sls-original.conf:/etc/sls/sls.conf
  moo-rist:
    image: moothecow/moo-rist-selfhosting-amd64:${VERSION}
    container_name: moo-rist
    restart: unless-stopped
    tty: true
    logging:
      driver: none
    environment:
      - RIST_RELAY_KEY=${RIST_RELAY_KEY}
    networks:
      network:
        ipv4_address: 172.19.0.2
    ports:
      - '2030:2030/udp'
    depends_on:
      - "moo-ffmpeg"
      - "moo-rist-logger"
  moo-rist-logger:
    image: moothecow/moo-rist-logger-selfhosting-amd64:${VERSION}
    container_name: moo-rist-logger
    restart: unless-stopped
    tty: true
    logging:
      driver: none
    networks:
      network:
        ipv4_address: 172.19.0.3
    volumes:
      - ./logfile.json:/opt/moostream/logfile.json
  moo-rist-stats:
    image: moothecow/moo-rist-stats-selfhosting-amd64:${VERSION}
    container_name: moo-rist-stats
    restart: unless-stopped
    tty: true
    logging:
      driver: none
    networks:
      network:
        ipv4_address: 172.19.0.4
    ports:
      - '8681:8080'
    volumes:
      - ./logfile.json:/opt/moostream/logfile.json
    depends_on:
      - "moo-rist-logger"
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
